/*
 * Ekubo API Client
 *
 * Сlient for Ekubo AMM DEX. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorResponse : Error response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "error")]
    pub error: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "status")]
    pub status: i32,
}

impl ErrorResponse {
    /// Error response
    pub fn new(error: std::collections::HashMap<String, serde_json::Value>, status: i32) -> ErrorResponse {
        ErrorResponse {
            error,
            status,
        }
    }
}

