/*
 * Ekubo API Client
 *
 * Сlient for Ekubo AMM DEX.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuoteResponse : The suggested route(s) to get the best price
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuoteResponse {
    #[serde(rename = "specifiedAmount")]
    pub specified_amount: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "route")]
    pub route: Vec<models::RoutePoint>,
}

impl QuoteResponse {
    /// The suggested route(s) to get the best price
    pub fn new(
        specified_amount: String,
        amount: String,
        route: Vec<models::RoutePoint>,
    ) -> QuoteResponse {
        QuoteResponse {
            specified_amount,
            amount,
            route,
        }
    }
}
