/*
 * Ekubo API Client
 *
 * Сlient for Ekubo AMM DEX. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Quotes : The suggested route(s) to get the best price
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Quotes {
    /// The result of all swaps (either an output amount if an exact input or an input if an exact output is specified). Sums up all amounts in every Quote.
    #[serde(rename = "total")]
    #[serde(deserialize_with = "crate::helpers::deserialize_felt_from_string")]
    pub total: starknet_core::types::Felt,
    #[serde(rename = "splits")]
    pub splits: Vec<models::Quote>,
}

impl Quotes {
    /// The suggested route(s) to get the best price
    pub fn new(total: starknet_core::types::Felt, splits: Vec<models::Quote>) -> Quotes {
        Quotes {
            total,
            splits,
        }
    }
}

