/*
 * Ekubo API Client
 *
 * Сlient for Ekubo AMM DEX.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QuoteResponse {
    Quote(models::Quote),
    Quotes(models::Quotes),
}

impl Default for QuoteResponse {
    fn default() -> Self {
        Self::Quote(Default::default())
    }
}
