/*
 * Ekubo API Client
 *
 * Сlient for Ekubo AMM DEX.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoutePoint {
    #[serde(rename = "pool_key")]
    pub pool_key: Box<models::PoolKey>,
    #[serde(rename = "sqrt_ratio_limit")]
    pub sqrt_ratio_limit: String,
    #[serde(rename = "skip_ahead")]
    pub skip_ahead: String,
}

impl RoutePoint {
    pub fn new(
        pool_key: models::PoolKey,
        sqrt_ratio_limit: String,
        skip_ahead: String,
    ) -> RoutePoint {
        RoutePoint {
            pool_key: Box::new(pool_key),
            sqrt_ratio_limit,
            skip_ahead,
        }
    }
}
